# Generated by Django 2.0.6 on 2018-07-17 09:09

import DjangoUeditor.models
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180716_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image1',
            field=stdimage.models.StdImageField(default='', upload_to=stdimage.utils.UploadToUUID(path='banner/2018/07'), verbose_name='轮播图11'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容描述'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
